### PR TITLE
Created the collaborative optimization strategy for the SSBJ case.

### PR DESCRIPTION
**Pull request by imcovangent**
I've added the collaborative optimization approach as a new script. Unfortunately it does not (yet) find the same optimum as the MDF and IDF approach, but the set-up is correct, I think. Could you have a look and maybe try the script with other optimizers you might have? Or do you see any problems in the script?

### CODE REVIEW

**Comment by relf** [comment]
Hi Imco. Thank you for this contribution. I just have a problem. I pulled your repo and when I test I get the following:
<pre>
(openmdao) D:\rlafage\workspace\SSBJ-OpenMDAO>git log -n 1
commit 4254dc36f531b11bab3901bb7b1e5b8015f6cb5c
Author: imcovangent <I.vanGent@tudelft.nl>
Date:   Mon Jun 18 22:18:44 2018 +0200

    Small bug fix and improvements of CO scripts.
(openmdao) D:\rlafage\workspace\SSBJ-OpenMDAO>python ssbj_co.py

===
Mda
===
NL: NLBGS Converged in 9 iterations
Traceback (most recent call last):
  File "ssbj_co.py", line 527, in <module>
    prob.model = model = SsbjCO(scalers=scalers, subopt_driver=subopt_driver)
  File "D:\rlafage\Miniconda2\envs\openmdao\lib\site-packages\openmdao\core\group.py", line 58, in __init__
    super(Group, self).__init__(**kwargs)
  File "D:\rlafage\Miniconda2\envs\openmdao\lib\site-packages\openmdao\core\system.py", line 365, in __init__
    self.metadata.update(kwargs)
  File "D:\rlafage\Miniconda2\envs\openmdao\lib\site-packages\openmdao\utils\options_dictionary.py", line 161, in update
    self[name] = in_dict[name]
  File "D:\rlafage\Miniconda2\envs\openmdao\lib\site-packages\openmdao\utils\options_dictionary.py", line 208, in __setitem__
    raise KeyError(msg.format(name))
KeyError: "Key 'subopt_driver' cannot be set because it has not been declared."

(openmdao) D:\rlafage\workspace\SSBJ-OpenMDAO>
</pre>  
It seems that <code>subopt_driver</code> declaration is not taken into account! I suppose you don't have this problem... I use OpenMDAO 2.2.1, I have not tried 2.3 which came out recently.
Any clue about what is going on?

**Comment by imcovangent** [comment]
I guess it has to do with the way the subopt_driver option is declared for the class `SsbjCO(Group)`. Now I use the `initialize` method (see line 455) while before these kind of keyword options were declared using the `__init__` method (I think), as is still the case with the `scaler` keyword argument in the SSBJ disciplines (structures, propulsion, etc.). So I guess putting it back to an `__init__` and changing it accordingly would make this work for version 2.2.1 (though I haven't tested it). I reran the script in 2.3 and there I'm sure the current script works. Would it not be an option to just update to 2.3? Or would you like to have the scripts compatible with 2.2.1 as well?

**Comment by relf** [comment]
I've just tested with OpenMDAO 2.3, it works without error... Though definitely not an efficient way to solve SSBJ test case! :wink: For me it is ok, we can live on the edge.

**Comment by imcovangent** [comment]
Nickel chrome! :) It's not very efficient indeed...

**Pull request merged**
