### PR TITLE
Created a script implementing the BLISS-2000 strategy on the SSBJ problem

### PR DESCRIPTION
**Pull request by imcovangent**
Hi Rémi and Sylvain, 

I've just finished an optimization and postprocessing script for the BLISS-2000 approach. Because of the random nature of the Latin Hypercube Sampling method the strategy does not always find the right optimum and sometimes gets stuck in other local optima. I have not found a solution for this yet, but it does always get very close to the real optimum in my runs.

Hope it's helpful. Let me know if you have any questions.

Cheers,
Imco

### CODE REVIEW

**Comment by imcovangent** [comment]
Hi Rémi and Sylvain,

I have updated (and debugged) the BLISS-2000 implementation that I made earlier. Now the strategy is much more stable and will find the right optimum, be it a lot less efficiently than MDF or IDF.

Can you let me know if it works for you and whether you will add this to the repository?

Salut!

Imco

**Comment by relf** [comment]
Hi Imco. Sorry for the late answer. I didn't test your PR. And now it seems there is a conflict. Could you check what is going on? And of course, I will be pleased to accept it.

**Comment by imcovangent** [comment]
Hi Rémi, I just solved the conflict. It should be mergeable now. :)
Salut

**Comment by relf** [comment]
Congrats Imco, you nailed it! I tested and got 3961.95!

**Comment by imcovangent** [comment]
Nickel chrome ! :) I was also testing the CO again, but that one gets stuck now for some reason. I'll have a look at it later, so you can expect a new pull request, I guess... ;)

**Comment by relf** [comment]
Ok. I've just tested MDF and IDF again. I will add travis automatic tests.

**Pull request merged**
